
variables:
  FIRST_VARIABLE: ''
  SECOND_VARIABLE: '123'
  ANOTHER_VARIABLE: ''
  THIRD_VARIABLE: 'abc'

jobs:
  - template: template.yml
    parameters:
      first: $(FIRST_VARIABLE)
      second: $(SECOND_VARIABLE)
      apples: ''

  - job: main_build
    pool:
      name: 'Hosted Ubuntu 1604'
    steps:
      - ${{ if ne('$(ANOTHER_VARIABLE)', '') }}:
          - pwsh: echo "'ANOTHER_VARIABLE' is not blank --$(ANOTHER_VARIABLE)--"
      - ${{ if eq('$(ANOTHER_VARIABLE)', '') }}:
          - pwsh: echo "'ANOTHER_VARIABLE' is blank --$(ANOTHER_VARIABLE)--"

      - ${{ if ne('$(THIRD_VARIABLE)', '') }}:
          - pwsh: echo "'THIRD_VARIABLE' is not blank --$(THIRD_VARIABLE)--"
      - ${{ if eq('$(THIRD_VARIABLE)', '') }}:
          - pwsh: echo "'THIRD_VARIABLE' is blank --$(THIRD_VARIABLE)--"

