
variables:
  FIRST_VARIABLE: ''
  SECOND_VARIABLE: '123'
  ANOTHER_VARIABLE: ''
  THIRD_VARIABLE: 'abc'

steps:
  - template: template.yml
    parameters:
      first: $(FIRST_VARIABLE)
      second: $(SECOND_VARIABLE)
      apples: ''
