
variables:
  FIRST_BLANK: ''
  FIRST_VALUE: '123'
  SECOND_BLANK: ''
  SECOND_VALUE: 'abc'

jobs:
  - template: template.yml
    parameters:
      firstBlank: $(FIRST_BLANK)
      firstValue: $(FIRST_VALUE)
      apples: ''

  - job: main_build
    pool:
      name: 'Hosted Ubuntu 1604'
    steps:
      - ${{ if ne('$(SECOND_BLANK)', '') }}:
          - pwsh: echo "'SECOND_BLANK' is not blank --$(SECOND_BLANK)--"
      - ${{ if eq('$(SECOND_BLANK)', '') }}:
          - pwsh: echo "'SECOND_BLANK' is blank --$(SECOND_BLANK)--"

      - ${{ if ne('$(SECOND_VALUE)', '') }}:
          - pwsh: echo "'SECOND_VALUE' is not blank --$(SECOND_VALUE)--"
      - ${{ if eq('$(SECOND_VALUE)', '') }}:
          - pwsh: echo "'SECOND_VALUE' is blank --$(SECOND_VALUE)--"

