
parameters:
  firstBlank: ''
  firstValue: ''
  apples: ''

jobs:
  - job: template_build
    pool:
      name: 'Hosted Ubuntu 1604'
    steps:
      - ${{ if ne(parameters.firstBlank, '') }}:
          - pwsh: echo "'firstBlank' is not blank --${{ parameters.firstBlank }}--"
      - ${{ if eq(parameters.firstBlank, '') }}:
          - pwsh: echo "'firstBlank' is blank --${{ parameters.firstBlank }}--"

      - ${{ if ne(parameters.firstValue, '') }}:
          - pwsh: echo "'firstValue' is not blank --${{ parameters.firstValue }}--"
      - ${{ if eq(parameters.firstValue, '') }}:
          - pwsh: echo "'firstValue' is blank --${{ parameters.firstValue }}--"

      - ${{ if ne(parameters.apples, '') }}:
          - pwsh: echo "'apples' is not blank --${{ parameters.apples }}--"
      - ${{ if eq(parameters.apples, '') }}:
          - pwsh: echo "'apples' is blank --${{ parameters.apples }}--"

      - ${{ if ne('$(SECOND_BLANK)', '') }}:
          - pwsh: echo "'SECOND_BLANK' is not blank --$(SECOND_BLANK)--"
      - ${{ if eq('$(SECOND_BLANK)', '') }}:
          - pwsh: echo "'SECOND_BLANK' is blank --$(SECOND_BLANK)--"

      - ${{ if ne('$(SECOND_VALUE)', '') }}:
          - pwsh: echo "'SECOND_VALUE' is not blank --$(SECOND_VALUE)--"
      - ${{ if eq('$(SECOND_VALUE)', '') }}:
          - pwsh: echo "'SECOND_VALUE' is blank --$(SECOND_VALUE)--"
